name: Ruby Gem

on:
  push:
    branches: [ "fvr-247" ]
    paths:
      - "lib/krane/version.rb"
  pull_request:
    branches: [ "fvr-247" ]
    paths:
      - "lib/krane/version.rb"

jobs:
  build:
    name: Build + Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Build the gem
      run: gem build krane.gemspec

    - name: Get gem file name
      id: get_gem_name
      run: echo "GEM_FILE=$(ls krane-*.gem)" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Gem to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.GEM_FILE }}
        asset_name: ${{ env.GEM_FILE }}
        asset_content_type: application/octet-stream
